### ISSUE TITLE
Mitigate threescale_api.errors.ApiClientError: Response(409 Conflict): b''

### ISSUE THREAD

**Issue by mganisin** [3scale-qe/3scale-tests#10]

**Comment by mganisin** [comment]
Fresh deployment of 3scale still requires some time to initialize returns some failures menawihle. A wating action is needed to ensure all is up and running

**Comment by mdujava** [comment]
Same can happen on https://github.com/3scale-qe/3scale-tests/blob/6588732634d4c15b02d5b44f9bebf8d290dc1c57/testsuite/tests/custom_tenant/test_custom_tenant.py#L41
